name: Work 1 Oz
on: push

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
    - name: Print Something
      run: echo "Hola Pitaya!"
    - name: Print Something 2
      run: echo "Esto es una impresión"