name: Test_1 Oz
on: push

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
    - name: Impresión
      run: echo "Esta es la impresión 1"
    - name: Impresión 2
      run: echo "Esta es la impresión 2"
    - name: Impresión 3
      run: echo "Esta es la impresión 3"
